# Generated by Django 3.2.3 on 2021-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_url",
                    models.TextField(unique=True, verbose_name="origin url"),
                ),
                (
                    "shortened_url",
                    models.CharField(max_length=64, verbose_name="shortened url"),
                ),
            ],
        ),
    ]
