# Generated by Django 3.2.3 on 2021-05-28 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(editable=False, max_length=128, verbose_name='shortened url'),
        ),
    ]
