# Generated by Django 3.2.3 on 2021-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_url_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="shortened_url",
            field=models.CharField(max_length=128, verbose_name="shortened url"),
        ),
    ]
