# Generated by Django 3.2.3 on 2021-05-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210528_1516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="shortened_url",
        ),
    ]
